management.endpoints.web.exposure.include: '*'

management.server.port: 8081
management.endpoint.health.probes.add-additional-paths: true

spring.web.resources.add-mappings: false
server.error.whitelabel.enabled: false